language: java
sudo: true
script:
- cd demo/
- mvn install -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api_key:
    secure: U7+vrXiWYTnOH6ywjTnK3OiBqmFPS3WbU2sGrfBecvAHnWrm/YFg+dOQPXIXhCIFKeOK1PYxJhVlZhGr4M1AgxnxP5hDBUTsv5Kr9aVn8vgJistTRwiS5C3mqeL2uvsEVZlFKdMOOlQoIYCjfgrxNLRtAcuCQBj8xQeUYC+QL1ocTTrPVTDIKkQTzJDyp8QNonif8gDdxVuc+UETHX/X6qHqBUoES5J8ltLRNda5vi4u0UtvsIjqRbRutvy+PyjrGHHeFVR8qHlawpx1bDbDMLB+MpJUQgsz3hRrGi+F/scn1lG53NcSmONEaqjve2yZ1ynEB09Ag3PocusGhFqMLxquMO2PMoFXxiKj3jU2xbkg1Gu7mU5wY1/3TelvLyQD9K0fYBHH5AbEO4IDCWSbvlMycw0w017vSHxVWYb6bZJ345ZsALoRgxd9FvQrxRMu09esd4GS4BOIyrpO7T8pZt08+Vgz9jYSDmsI/3Dsg+t/SMNvfhjfBZeZyelPoMhvyT1GN7gwDLTnO6+PyvEeYDGX+3+3mWe1MZKniRXpvIdS0QEk+2G2CIfdykBpZ2VbrGnsFF8TmpzFuz7dg/AajPRsVdAmDS4EMsFFLJCftmRXJMqoEfJlcRvx/OavsCl/9XeMqjyf1W4gmB8SH2GDV3LDA0ic3LeewValga6mQ7w=
  app: travis-ci-practice
  on:
    repo: danielsmithm/travis-ci-practice
    branch: develop
